### ISSUE TITLE
Newer builds of same commit are discarded

### ISSUE THREAD

**Issue by Bilge** [codecov/support#480] opened 2018-02-21 18:16 UTC
If a cron job is configured to run on a specific branch and that branch doesn't move forward (i.e. it continues to point to the same commit) all newer builds will be discarded and it will continue to show the oldest coverage report.

I posit that newer builds should either replace, or append to, older ones.

For example, the [Porter coverage for master](https://codecov.io/gh/ScriptFUSION/Porter/branch/master) claims the branch has not been updated for 4 months. That's true, if we're just talking about the code, but there has been a [daily cron running on the branch every day](https://travis-ci.org/ScriptFUSION/Porter/builds) during those four months and all of the coverage reports have been discarded by Codecov.

**Comment by stevepeak** [comment] 2018-03-07 10:28
Hi @Bilge  Commits are always merged, never discarded. However, there could be an issue with the cache where the branch is out of date. My question would be: are the reports accurate though?

I can review our caching policy in the meantime.

**Comment by Bilge** [comment] 2018-03-07 11:31
In the case of Porter, the report is still accurate. However, I experienced this problem with [PIEP](https://github.com/ScriptFUSION/PHPUnit-Immediate-Exception-Printer) where external updates to dependencies caused coverage to improve significantly, despite the repository code not changing, but the changes were not reflected in Codecov's reports until a new commit was pushed. For proof, please see ScriptFUSION/PHPUnit-Immediate-Exception-Printer#11, which was a blank PR that significantly improved code coverage.

**Comment by stevepeak** [comment] 2018-03-07 13:50
Ok. I believe I understand what your team is doing. However, I'm confused... New reports always append in Codecov. TBO I'm not sure what the issue is.

> all newer builds will be discarded 

This is not the case in Codecov, we merge them all.

**Comment by stevepeak** [comment] 2018-03-07 13:52
I'm going to close, respectfully, because it seems to be repository specific. We will be happy to continue support on this issue while closed.

**Closed by stevepeak** 2018-03-07 13:52 UTC

**Comment by Bilge** [comment] 2018-03-07 14:06
How could it be repository specific? There's nothing unique or special about one specific repository. Daily builds are not updated on Codecov unless the commit hash changes. That's a general problem, not a specific problem.
