### ISSUE TITLE
Overview and bagde is not updating

### ISSUE THREAD

**Issue by cloutiertyler** [codecov/support#316] opened 2016-10-31 06:37 UTC
It seems like I have the exact same issue as #286. I forced push my repo (terribly I know) and now I'm not seeing an updated overview.

https://codecov.io/gh/SwiftOnEdge/Edge

Would it be possible to fix this error?

**Comment by stevepeak** [comment] 2016-11-14 16:43
Hey! Sorry for the delay, just had a baby 👶 🎉 

Your project seems on track. What is the latest force-push commit I can investigate? Are you able to reproduce this issue? 

Thank you!

**Comment by stevepeak** [comment] 2017-02-23 21:26
@cloutiertyler How is this looking? Sorry for the delay. Closing because [this looks](https://codecov.io/gh/SwiftOnEdge/Edge) nice 👍

**Closed by stevepeak** 2017-02-23 21:26 UTC

**Comment by cloutiertyler** [comment] 2017-02-24 22:08
Yep, I was able to resolve this problem, although I can't remember what the fix was. Thanks for the help though!
