### ISSUE TITLE
Display what has changed

### ISSUE THREAD

**Issue by RyanCopley** [codecov/support#9] opened 2015-05-20 21:20 UTC
It would be nice to be able to see what "changed", as like this:

![7iezqdmbycgxbfup39md32pelq2nrr0oe4fxle1ztki](https://cloud.githubusercontent.com/assets/819591/7736812/7800a9b6-ff14-11e4-9242-ba25b3cc5fb4.jpg)

**Comment by stevepeak** [comment] 2015-06-18 23:17
Moved/Duplicate of #20. Thanks!

**Closed by stevepeak** 2015-06-18 23:17 UTC
Labels: duplicate, feature
