### ISSUE TITLE
Codecov commit history is out of date

### ISSUE THREAD

**Issue by ezzatron** [codecov/support#267] opened 2016-08-02 05:26 UTC
If you compare these commit histories for the `master` branch:
- [Codecov's commit history](https://codecov.io/gh/eloquent/phony/branch/master/commits)
- [GitHub's commit history](https://github.com/eloquent/phony/commits/master)

You'll see that at the time of writing, the _real_ latest commit on the `master` branch is [f5d7dc1](https://github.com/eloquent/phony/commit/f5d7dc1d0862dae5d1797a12b5c6eddf8ec7df17). Codecov is about 2 months and almost 40 commits behind at this point.

Why is this happening? Well, it's not that the reports aren't being uploaded. For instance, [here is the Codecov report for f5d7dc1](https://codecov.io/gh/eloquent/phony/commit/f5d7dc1d0862dae5d1797a12b5c6eddf8ec7df17), the latest commit on master at the time of writing. Notice that Codecov still thinks this commit is on the `scrutinizer` branch, a temporary feature branch that no longer exists.

My guess is that since I use "fast-forward" merging when I merge feature branches, there is no "new" commit hash being created, and Codecov never detects that the commits have moved from one branch to another.

For further evidence, please see these two Travis build logs, which show both the original report submission, and the repeated submission from `master`:
- [Original submission from `scrutinizer`](https://travis-ci.org/eloquent/phony/jobs/149075766#L469)
- [Repeat submission from `master`](https://travis-ci.org/eloquent/phony/jobs/149078861#L510)

It also seems to point to a bigger problem, in that Codecov doesn't appear to handle a commit existing in multiple branches simultaneously.

Please let me know if I can assist with further information.

**Comment by cbalea** [comment] 2016-08-02 09:28
I am encountering the same problem: https://github.com/codecov/codecov-bash/commit/923daecf2464a6a008786c4332b8ebc6a64bd0f2#commitcomment-18428828

**Comment by stevepeak** [comment] 2016-08-02 16:45
@ezzatron thank you for asking these questions.

> Codecov is about 2 months and almost 40 commits behind at this point.

Codecov **only** shows commits that have uploaded reports and not every commit in GitHub. So if no reports were uploaded for a period of time it will remain aged compared to the Github repository. It appears that your script is not uploading coverage reports when I reviewed a couple of your latest builds on travis. I suspect [these lines are never called](https://github.com/eloquent/phony/blob/master/scripts/travis-after#L34-L36)

**Comment by stevepeak** [comment] 2016-08-02 16:47
@cbalea the referenced code you have provided is not yet deployed. Merge commits are a very complex concept and are still being reviewed across the platform.

We do change the commits sha for Merge commits to their "actual" commit. For example: `Merage abc into xyz` would become `abc` when uploaded.

**Comment by ezzatron** [comment] 2016-08-03 00:01
@stevepeak That is **not** the case. The reports are definitely being uploaded. Here is an excerpt from the `master` build that I have [already linked in this issue](https://travis-ci.org/eloquent/phony/jobs/149078861#L510):

```
$ scripts/travis-after
TRAVIS_PHP_VERSION is '7.0'
TRAVIS_BRANCH is 'master'
TRAVIS_TAG is ''
TRAVIS_PULL_REQUEST is 'false'
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-c84d39e
==> Travis CI detected.
    project root: .
==> Running gcov disable via -X gcov
    -> Running gcov in .
==> Searching for coverage reports in:
    +  .
    -> Found 2 reports
==> Python coveragepy not found
==> Detecting git/mercurial file structure
==> Reading reports
    + ./coverage/coverage.xml bytes=503384
    + ./coverage/coverage.txt bytes=13582
==> Appending adjustments (http://bit.ly/1O4eBpt)
    + Found 10968 adjustments
==> Uploading reports
    url: https://codecov.io
    query: branch=master&commit=f5d7dc1d0862dae5d1797a12b5c6eddf8ec7df17&build=1511.5&build_url=&tag=&slug=eloquent/phony&yaml=&service=travis&flags=&pr=false&job=149078861
    -> Pinging Codecov
    -> Uploading to S3 https://codecov.s3.amazonaws.com
    -> View reports at http://codecov.io/github/eloquent/phony/commit/f5d7dc1d0862dae5d1797a12b5c6eddf8ec7df17
```

Important points in this excerpt:
- TRAVIS_BRANCH is 'master'
- View reports at http://codecov.io/github/eloquent/phony/commit/f5d7dc1d0862dae5d1797a12b5c6eddf8ec7df1

**Comment by glennmatthews** [comment] 2016-08-05 19:38
I'm seeing similar behavior. In my case it appears to be because my commits to master are also tags, and while Travis-CI is running once for the tag and once for master, these have the same SHA and so CodeCov is only recognizing the tag commit and not the master commit:

[v1.7.0 tag build on Travis](https://travis-ci.org/glennmatthews/cot/builds/150126917):
```
==> Uploading
    .url https://codecov.io
    .query build=400.5&pr=false&yaml=codecov.yml&slug=glennmatthews%2Fcot&commit=a11b2721f8cc2ab505b4558d1450f091dee0dcd0&service=travis&branch=v1.7.0&job=150126922&package=py2.0.5&tag=v1.7.0
    Pinging Codecov...
    Uploading to S3...
    http://codecov.io/github/glennmatthews/cot/commit/a11b2721f8cc2ab505b4558d1450f091dee0dcd0
```
[master build on Travis](https://travis-ci.org/glennmatthews/cot/builds/150126941):
```
==> Uploading
    .url https://codecov.io
    .query job=150126946&yaml=codecov.yml&package=py2.0.5&commit=a11b2721f8cc2ab505b4558d1450f091dee0dcd0&service=travis&slug=glennmatthews%2Fcot&branch=master&pr=false&build=401.5
    Pinging Codecov...
    Uploading to S3..
    http://codecov.io/github/glennmatthews/cot/commit/a11b2721f8cc2ab505b4558d1450f091dee0dcd0
```

Note that one uses `&branch=v1.7.0...&tag=v1.7.0` while the other uses `&branch=master` but they both have the same commit hash. Codecov seems to only [recognize this commit as v1.7.0](https://codecov.io/github/glennmatthews/cot/commit/a11b2721f8cc2ab505b4558d1450f091dee0dcd0) and does not also update master.

**Comment by stevepeak** [comment] 2016-08-06 16:54
@glennmatthews unfortunately at this moment tags are not supported in Codecov UI. Is there a way to temporarily disable uploading coverage on tag builds for travis? Using something like

```bash
[ "$TRAVIS_TAG" = "" ] && bash <(curl -s https://codecov.io/bash) || echo 'Ignore coverage'
```

Thank you!

**Comment by glennmatthews** [comment] 2016-08-08 14:09
@stevepeak Thanks for the suggestion. For the moment, the following in my .travis.yml seems to work:

```yaml
after_success:
  if [ -z "$TRAVIS_TAG" ]; then
    codecov;
  else
    echo "Tag build ($TRAVIS_TAG). Not uploading coverage.";
  fi
```

**Comment by ezzatron** [comment] 2016-11-04 05:06
Not sure when it got fixed, but the original issue I reported seems to be fixed for me. Thanks @stevepeak! Happy for you to close if you like.

**Comment by stevepeak** [comment] 2016-11-07 14:53
There have been many improvements to our backend that may have contributed to fixing this issue. I'll close this for now. If any problems occur from here please create a **new issue**. Thank you friends 👍

**Closed by stevepeak** 2016-11-07 14:53 UTC

**Comment by greenlaw110** [comment] 2017-09-01 04:00
@stevepeak looks like I have the same issue. The [travis-ci build](https://travis-ci.org/osglworks/java-unit/builds/270675908) shows everything is fine:

![image](https://user-images.githubusercontent.com/216930/29954771-9340d94e-8f1d-11e7-81b9-a074fc51ee60.png)


But codecov says the [commits is still 7 days ago](https://codecov.io/gh/osglworks/java-unit/commits):

![image](https://user-images.githubusercontent.com/216930/29954727-55d9cb92-8f1d-11e7-91dd-dcac0178ce73.png)

**Comment by greenlaw110** [comment] 2017-09-01 22:30
okay it is caused by missing the `cobertura-maven-plugin` in the project `pom.xml` file. Added that plugin and it's okay now
