### ISSUE TITLE
Dashboard (and badge) report coverage for the most recent build from the pull request instead of master branch

### ISSUE THREAD

**Issue by tjanez** [codecov/support#229] opened 2016-06-13 08:35 UTC
We've just started using [Codecov for our project](https://codecov.io/gh/genialis/resolwe-runtime-utils/). We've noticed that the dashboard and the badge show coverage for the most recent build from the pull request instead of the most recent build from the `master` branch. Here are screenshots showing the problem:

![codecov-wrong-coverage](https://cloud.githubusercontent.com/assets/2518544/16001371/e71341ae-3151-11e6-9451-9e86b172b861.png)

![codecov-wrong-coverage-badge](https://cloud.githubusercontent.com/assets/2518544/16001431/3be192a8-3152-11e6-9c02-927628ce6058.png)

**Comment by skirpichev** [comment] 2016-06-21 13:37
I think it's a duplicate of https://github.com/codecov/support/issues/191

**Comment by tjanez** [comment] 2016-06-21 14:42
@skirpichev, yes, it's probably the same. At the time of writing, the [original reported said his example is gone](https://github.com/codecov/support/issues/191#issuecomment-224747856), that's why I rather opened a new issue.

**Comment by stevepeak** [comment] 2016-07-20 21:38
Moving this issue to #191 Thanks!

**Closed by stevepeak** 2016-07-20 21:38 UTC
