### ISSUE TITLE
Code coverage for new files shows 0% coverage, when it's actually 100%

### ISSUE THREAD

**Issue by yyunikov** [codecov/support#421] opened 2017-07-11 12:55 UTC
New file was created in PR and was fully covered with test. It was successfully submitted to CodeCov, however shows 0% coverage for the file. See the screenshots below
![circle_ci](https://user-images.githubusercontent.com/5285857/27915981-7b1ff068-6270-11e7-8f2e-799a560aa25d.png)
![codecov_console](https://user-images.githubusercontent.com/5285857/27916408-9fb9e6b2-6271-11e7-96af-bf4345463df1.png)

And the actual GitHub files:

![new-file](https://user-images.githubusercontent.com/5285857/27915982-7b3c0d66-6270-11e7-8019-1a69acac669b.png)
![test-file](https://user-images.githubusercontent.com/5285857/27915984-7d0b76cc-6270-11e7-87e0-aa67d3fa7c20.png)

The report also shows 0% coverage, but actual Jacoco report shows different result:
![report](https://user-images.githubusercontent.com/5285857/28163023-0d273ba4-67d2-11e7-9704-8353f94923f9.png)
![jacoco](https://user-images.githubusercontent.com/5285857/28163050-2dd8c714-67d2-11e7-9fe6-2d3405b111e5.png)
How is that possible?

**Comment by yyunikov** [comment] 2017-07-11 12:55
I’ve created a test repo to reproduce an issue and it reproduces without a doubt. Please check:
https://github.com/yyunikov/codecov-example-java/pull/4/files
Report is below:
https://codecov.s3.amazonaws.com/v4/raw/2017-07-11/8811583BD8872206B00EB166993138A4/9486f313f4298d31111f2b9f98ef2177bd370259/6bb44336-05dc-4118-8819-7930549fd8a8.txt
![codecov1](https://user-images.githubusercontent.com/5285857/28069055-b014684c-6650-11e7-8a39-c6720de0fd2f.png)
![codecov2](https://user-images.githubusercontent.com/5285857/28069054-b01009b4-6650-11e7-9b90-cea389362db9.png)

**Comment by stevepeak** [comment] 2017-07-17 07:46
Closing since this is a per-project issue. Furthermore, the issue is with jacoco xml not Codecov. Thanks

**Closed by stevepeak** 2017-07-17 07:46 UTC
